;; -*- mode: Lisp; -*-
(source melpa) ; melpa.org
(source gnu) ; https://elpa.gnu.org/
; (source marmalade) ; "https://marmalade-repo.org/packages/"

(depends-on "ag") ; needed for projectile-ag
(depends-on "avy")
(depends-on "bm") ; visual bookmarks
(depends-on "cask")
(depends-on "dash")
(depends-on "diminish")
(depends-on "editorconfig")
(depends-on "company")
(depends-on "emmet-mode")
(depends-on "f")
;(depends-on "flycheck")
;(depends-on "flycheck-cask")
(depends-on "ggtags")
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-emmet")
(depends-on "helm-gtags")
(depends-on "helm-projectile")
(depends-on "htmlize")
(depends-on "idle-highlight-mode") ; needs configuration. also consider http://emacsblog.org/2007/04/17/quick-tip-light-symbol-mode/ ?
; TODO: http://oremacs.com/2015/04/16/ivy-mode/
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "multiple-cursors")
(depends-on "move-dup") ; Copy/move line(s) up or down
(depends-on "neotree")
(depends-on "php-mode" :git "https://github.com/ejmr/php-mode.git")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "sass-mode")
(depends-on "smooth-scrolling")
(depends-on "transpose-frame")
(depends-on "use-package")
(depends-on "vlf") ; very large file
(depends-on "web-mode")
(depends-on "wolfram") ; https://github.com/hsjunnesson/wolfram.el
(depends-on "yasnippet")

; Themes
(depends-on "zenburn-theme")
(depends-on "solarized-theme") 
(depends-on "ample-theme") 
