#!/usr/bin/env bash
export DEBIAN_FRONTEND=noninteractive
add-apt-repository -y ppa:ubuntu-elisp
apt-get update > /dev/null
apt-get -y install emacs-snapshot
apt-get -y install ncurses-term
update-alternatives --set emacs /usr/bin/emacs-snapshot
#su -c "curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python" vagrant
#echo 'export PATH="/home/vagrant/.cask/bin:$PATH"' >> /home/vagrant/.bashrc
# su -c "cd /home/vagrant/.dotfiles && ./install -c ter.conf.yaml" vagrant
